### ISSUE TITLE
Create event (def shef 40) More Monad Challenges

### ISSUE THREAD

**Issue by defshef-auto** [defshef/defshef.github.io#10]
<div class="row">
  <article class="meeting all-columns" id="defshef40">
    <a name="defshef40"></a>
    <h2>(def shef 40) More Monad Challenges</h2>
    <p class="meeting-info"> Tuesday October 10, 2017 - 6:30pm
       - <a href="https://www.google.com/maps/search/?api=1&query=Rutland Arms, 86 Brown Street, Sheffield, S1 2BS></a>
       - <a href="https://www.eventbrite.co.uk/e/def-shef-40-more-monad-challenges-tickets-37913945632">Tickets</a>
    </p>
    <P>We had a look at the <A HREF="http://mightybyte.github.io/monad-challenges/" TARGET="_blank" TITLE="Monad Challenges" REL="noreferrer noopener nofollow noopener noreferrer nofollow">The Monad Challenges</A> in August's <A HREF="http://defshef.github.io/#ep38" TARGET="_blank" TITLE="(def shef 38)" REL="noreferrer noopener nofollow noopener noreferrer nofollow">(def shef 38)</A>. They're a thought-provoking set of problems to solve, designed to help you "discover" monads rather than teach them to you.<BR></P>
<P>We enjoyed the last session and so we're revisiting! The Monad Challenges are written in Haskell, but I think you could have a go in other functional languages too.</P>
<P>(def shef) is open to all, beginners and experts alike. If you're new to functional programming, we'd love you to come along and wel'll help you get started!</P>
<P>We thank Sky Betting and Gaming for kindly sponsoring this event. <A HREF="http://appointments.thesundaytimes.co.uk/article/best100companies/" TARGET="_blank" REL="noreferrer noopener nofollow noopener noreferrer nofollow">One of the Sunday Times' Top 100 companies to work for</A>, based in Leeds and Sheffield, there are all sorts of <A HREF="http://engineering.skybettingandgaming.com/jobs/" TARGET="_blank" REL="noreferrer noopener nofollow noopener noreferrer nofollow">roles available now</A>.</P>
    <aside>(def shef) thanks Sky Betting and Gaming for kindly sponsoring this event.
      <a href="http://appointments.thesundaytimes.co.uk/article/best100companies/">One of the Sunday Times' Top 100 companies to work for</a>, based in Leeds and Sheffield, there are
      <a href="http://engineering.skybettingandgaming.com/jobs/">roles available now</a>.<aside>
  </article>
</div>

**Comment by brabster** [comment]
Done
